# Generated by Django 3.1.6 on 2021-02-12 11:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='To',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='delivered_by',
        ),
        migrations.AlterField(
            model_name='event',
            name='correlation_id',
            field=models.UUIDField(default=uuid.UUID('efcf0ac5-cbca-4813-a65a-95a151457cc8'), unique=True),
        ),
    ]
