# Generated by Django 3.1.6 on 2021-02-15 13:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210215_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPainInformation',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.useraccount')),
                ('inn', models.CharField(max_length=12, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='inn',
        ),
        migrations.AlterField(
            model_name='event',
            name='correlation_id',
            field=models.UUIDField(default=uuid.UUID('8f74a37c-5759-494a-a0fd-eb8e4297919f'), unique=True),
        ),
    ]
