# Generated by Django 3.1.6 on 2021-02-15 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210215_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpaininformation',
            name='director',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userpaininformation',
            name='full_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userpaininformation',
            name='kpp',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='userpaininformation',
            name='legal_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userpaininformation',
            name='ogrn',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='userpaininformation',
            name='okpo',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userpaininformation',
            name='oktmo',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='userpaininformation',
            name='state_status',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='correlation_id',
            field=models.UUIDField(default=uuid.UUID('99da6ac2-695b-434f-95d9-3bd9d81ad244'), unique=True),
        ),
        migrations.AlterField(
            model_name='userpaininformation',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
