# Generated by Django 3.1.6 on 2021-02-18 14:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210216_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtransfer',
            name='total',
            field=models.FloatField(default=1000),
        ),
        migrations.AlterField(
            model_name='event',
            name='correlation_id',
            field=models.UUIDField(default=uuid.UUID('784c737c-c3f5-4d76-8454-c470dc3c1cf6'), unique=True),
        ),
        migrations.AlterField(
            model_name='itemtransfer',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
