# Generated by Django 3.1.6 on 2021-02-19 11:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210218_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientManager',
            fields=[
                ('email', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='correlation_id',
            field=models.UUIDField(default=uuid.UUID('814567ee-bad1-4631-ba86-acfaa39bb28c'), unique=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='manager',
            field=models.ForeignKey(default='admin@admin.ru', on_delete=django.db.models.deletion.DO_NOTHING, to='app.clientmanager'),
        ),
    ]
